# Write service manefest file for kubernetes
apiVersion: v1
kind: Service
metadata:
  name: pyapp-service
  labels:
    app: pyapp
spec:
  selector:
    app: pyapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
